services:
  server:
    container_name: progchess_sandbox
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock